name: Release

on: [workflow_dispatch]

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - uses: jwsi/submodule-checkout@v1
        with:
          version: 0.13.0
      - run: |
         zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux-musl
         xz -zc zig-out/bin/droidux > droidux-x86_64-linux-musl.xz 
         zig build -Doptimize=ReleaseFast -Dtarget=aarch64-linux-musl
         xz -zc zig-out/bin/droidux > droidux-aarch64-linux-musl.xz 
         zig build -Doptimize=ReleaseFast -Dtarget=riscv64-linux-musl
         xz -zc zig-out/bin/droidux > droidux-riscv64-linux-musl.xz 

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            droidux-x86_64-linux-musl.xz
            droidux-aarch64-linux-musl.xz
            droidux-riscv64-linux-musl.xz
          tag_name: ${{ steps.vars.outputs.sha_short }}
          make_latest: true
