name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build test --summary all
